# Generated by Django 5.1.1 on 2024-10-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expensesuserdataincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesusers',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
